"""Look for exact modular invariants in the signed-NAE/Ising energy."""

from __future__ import annotations

import json
import math
import random
from functools import reduce
from pathlib import Path

from signed_nae_core import build_ising, enumerate_clauses, oriented_edges


HERE = Path(__file__).resolve().parent
OUT = HERE / "outputs"


def gf2_rank(rows: list[int]) -> int:
    rows = rows[:]
    rank = 0
    while rows:
        pivot = max(rows)
        if pivot == 0:
            break
        rows.remove(pivot)
        bit = 1 << (pivot.bit_length() - 1)
        rows = [row ^ pivot if row & bit else row for row in rows]
        rank += 1
    return rank


def energy(pairs: int, jmat: list[list[int]], bits: list[int]) -> int:
    spins = [1 if b == 0 else -1 for b in bits]
    numerator = pairs + sum(
        jmat[i][j] * spins[i] * spins[j]
        for i in range(len(jmat))
        for j in range(i + 1, len(jmat))
    )
    assert numerator % 4 == 0
    return numerator // 4


def analyse(name: str, m: int, edges, known_bits=None) -> dict:
    clauses = enumerate_clauses(m, [tuple(e) for e in edges])
    pairs_list, jmat, missing = build_ising(len(edges), clauses)
    assert not missing
    pairs = len(pairs_list)
    n = len(jmat)
    weights = [abs(jmat[i][j]) for i in range(n) for j in range(i + 1, n) if jmat[i][j]]
    row_sums = [sum(row) for row in jmat]

    # Flipping spin i from the all-plus state changes V by -row_sum_i/2.
    # Changing any other sign changes that delta by an integer J_ij. Thus the
    # gcd below is the exact additive lattice generated by all one-spin moves.
    delta_generators = []
    integral_flip_lattice = all(x % 2 == 0 for x in row_sums)
    if integral_flip_lattice:
        delta_generators.extend(abs(x // 2) for x in row_sums)
        delta_generators.extend(weights)
    energy_lattice_gcd = reduce(math.gcd, delta_generators, 0) if delta_generators else 0

    odd_rows = []
    for i in range(n):
        mask = 0
        for j in range(n):
            if jmat[i][j] & 1:
                mask |= 1 << j
        odd_rows.append(mask)

    rng = random.Random(20260717 + sum(sum(e) for e in edges))
    samples = [[rng.getrandbits(1) for _ in range(n)] for _ in range(5000)]
    values = [energy(pairs, jmat, bits) for bits in samples]
    all_plus = energy(pairs, jmat, [0] * n)
    result = {
        "name": name,
        "clauses": len(clauses),
        "pairs": pairs,
        "nonzero_couplings": len(weights),
        "coupling_gcd": reduce(math.gcd, weights, 0),
        "all_couplings_even": all(w % 2 == 0 for w in weights),
        "row_sums_even": integral_flip_lattice,
        "energy_lattice_gcd": energy_lattice_gcd,
        "odd_coupling_matrix_gf2_rank": gf2_rank(odd_rows),
        "all_plus_energy": all_plus,
        "sampled_residues": {
            str(mod): sorted({v % mod for v in values}) for mod in (2, 4, 8)
        },
        "sample_min": min(values),
    }
    if known_bits is not None:
        result["known_energy"] = energy(pairs, jmat, known_bits)
    return result


def load_cases():
    cases = json.loads((HERE / "cases.json").read_text(encoding="utf-8"))["cases"]
    signed = json.loads((OUT / "signed_nae_results.json").read_text(encoding="utf-8"))["cases"]
    signed_by_name = {case["name"]: case for case in signed}
    out = []
    for case in cases:
        record = signed_by_name[case["name"]]
        edges, bits = oriented_edges(case)
        if record.get("exact", {}).get("bits") is not None:
            bits = record["exact"]["bits"]
        out.append((case["name"], case["m"], edges, bits))

    neighbours = json.loads(
        (OUT / "spectral_neighbor_results.json").read_text(encoding="utf-8")
    )["exact"]
    for record in neighbours:
        if record["solve"].get("violations") == 16:
            out.append(
                (
                    f"m37_plateau_rank{record['rank']}",
                    37,
                    record["candidate"]["edges"],
                    record["solve"]["bits"],
                )
            )
    return out


def main():
    results = [analyse(*case) for case in load_cases()]
    for item in results:
        print(
            item["name"],
            "clauses=", item["clauses"],
            "known=", item.get("known_energy"),
            "gcd=", item["energy_lattice_gcd"],
            "rank2=", item["odd_coupling_matrix_gf2_rank"],
            "res4=", item["sampled_residues"]["4"],
        )
    (OUT / "mod_energy_results.json").write_text(
        json.dumps(results, indent=2), encoding="utf-8"
    )


if __name__ == "__main__":
    main()
