"""Enumerate bases generated by the C4 orbit of one permutation."""

from __future__ import annotations

import argparse
import itertools
import json
import time

from four_permutation_lift_sat import solve


def rotate_permutation(permutation: tuple[int, ...]) -> tuple[int, ...]:
    m = len(permutation)
    result = [-1] * m
    for x, y in enumerate(permutation):
        result[m - 1 - y] = x
    return tuple(result)


def orbit(permutation: tuple[int, ...]) -> tuple[tuple[int, ...], ...]:
    layers = []
    current = permutation
    for _ in range(4):
        layers.append(current)
        current = rotate_permutation(current)
    return tuple(layers)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--m", type=int, required=True)
    parser.add_argument("--time-limit", type=float, default=3.0)
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--maximum-hits", type=int, default=0)
    args = parser.parse_args()

    tested = 0
    status_counts: dict[str, int] = {}
    hits = 0
    simple_bases = 0
    started = time.perf_counter()
    for permutation in itertools.permutations(range(args.m)):
        layers = orbit(permutation)
        if permutation != min(layers):
            continue
        tested += 1
        edges = [
            (x, layer[x])
            for layer in layers
            for x in range(args.m)
        ]
        if len(set(edges)) == len(edges):
            simple_bases += 1
        result = solve(
            args.m,
            [list(layer) for layer in layers],
            time_limit=args.time_limit,
            workers=args.workers,
        )
        status = result["status"]
        status_counts[status] = status_counts.get(status, 0) + 1
        if status in ("OPTIMAL", "FEASIBLE"):
            hits += 1
            print(
                json.dumps(
                    {
                        "hit": hits,
                        "generator": permutation,
                        "orbit_layers": layers,
                        "simple_base": len(set(edges)) == len(edges),
                        "result": result,
                    },
                    indent=2,
                ),
                flush=True,
            )
            if args.maximum_hits and hits >= args.maximum_hits:
                break
        if tested % 100 == 0:
            print(
                json.dumps(
                    {
                        "progress": tested,
                        "simple_bases": simple_bases,
                        "hits": hits,
                        "status_counts": status_counts,
                        "wall_seconds": time.perf_counter() - started,
                    }
                ),
                flush=True,
            )
    print(
        json.dumps(
            {
                "summary": True,
                "m": args.m,
                "tested_orbit_representatives": tested,
                "simple_bases": simple_bases,
                "hits": hits,
                "status_counts": status_counts,
                "wall_seconds": time.perf_counter() - started,
            },
            indent=2,
        ),
        flush=True,
    )


if __name__ == "__main__":
    main()
