"""
Mine REAL C4 (rot4) solutions: extract the 2-factor (edge set), its cycle
structure, and -- crucially -- test whether the single-m-cycle real
solutions use the GOLDEN-RATIO (low-discrepancy / quasicrystal) vertex order.

If real single cycles match the golden order, that is direct evidence for the
user's "low-D disorder = projection of high-D order" intuition: the C4
solutions are literally generated by a 1D cut-and-project (Sturmian) sequence.
"""

import os, math
from collections import defaultdict, Counter

ALPHABET = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
CACHE = 'flammenkamp_cache'

def decode(line, n):
    line = line.strip()
    if len(line) < 2:
        return None
    body = line[1:]
    if len(body) != 2 * n:
        return None
    pts = []; per = len(body) // n
    for y in range(n):
        for j in range(per):
            ch = body[y * per + j]
            if ch not in ALPHABET:
                return None
            pts.append((ALPHABET.index(ch), y))
    return pts

def edges_of(pts, n):
    m = n // 2
    return sorted(set((x, y) if x <= y else (y, x) for x, y in pts if x < m and y < m))

def cycle_decomp(edges, m):
    adj = defaultdict(list)
    for a, b in edges:
        adj[a].append(b); adj[b].append(a)
    seen = set(); res = []
    for s in range(m):
        if s in seen or s not in adj:
            continue
        cur = s; prev = -1; length = 0; path = []
        while cur not in seen:
            seen.add(cur); path.append(cur)
            nx = [w for w in adj[cur] if w != prev]
            if not nx:
                break
            prev, cur = cur, nx[0]; length += 1
        if length:
            res.append(length)
    return sorted(res, reverse=True)

def canonical(edges, m):
    # single cycle only -> canonical sequence
    adj = defaultdict(list)
    for a, b in edges:
        adj[a].append(b); adj[b].append(a)
    # find cycle containing 0
    cur = 0; prev = -1; seq = []
    while True:
        seq.append(cur)
        nx = [w for w in adj[cur] if w != prev]
        if not nx:
            break
        prev, cur = cur, nx[0]
        if cur == 0:
            break
    # rotate to start at 0 (already), choose direction
    rev = seq[::-1]
    def rot_to_0(s):
        i = s.index(0)
        return s[i:] + s[:i]
    c1 = rot_to_0(seq); c2 = rot_to_0(rev)
    return tuple(min(c1, c2))

def golden_canonical(m, alpha=1.618033988749895):
    order = sorted(range(m), key=lambda k: (k * alpha) % 1)
    edges = [(order[k], order[(k + 1) % m]) for k in range(m)]
    return canonical(edges, m)

def main():
    print("=== real rot4 2-factor structure (cycle-length distribution) ===")
    match_report = []
    for n in range(6, 74, 2):
        f = f'{CACHE}/n{n}_rot4'
        if not os.path.exists(f):
            continue
        m = n // 2
        sols = []
        with open(f) as fh:
            for line in fh:
                p = decode(line, n)
                if p:
                    sols.append(p)
        if not sols:
            continue
        dist = Counter()
        single_canons = set()
        for p in sols:
            e = edges_of(p, n)
            c = cycle_decomp(e, m)
            dist[tuple(c)] += 1
            if c == [m]:
                single_canons.add(canonical(e, m))
        top = sorted(dist.items(), key=lambda x: -x[1])[:4]
        single = dist.get((m,), 0)
        print(f"n={n:2d} m={m:2d} sols={len(sols):6d} single_mcycle={single:6d} "
              f"top_cyc={top}")
        # compare single cycles to golden order
        gcan = golden_canonical(m)
        hit = gcan in single_canons
        match_report.append((m, len(single_canons), hit))
    print("\n=== golden-order match in real single-m-cycles ===")
    for m, nsc, hit in match_report:
        if nsc > 0:
            print(f"m={m:2d}  #distinct_single_cycles={nsc:5d}  golden_present={hit}")

main()
