"""
generate_hint_heatmap.py -- build a soft "suggestion" heatmap for the m=37
rot4-NTIL manual builder.

m=37 has no known solution, so suggestions can only be *extrapolated*: take every
known small-m rot4 solution (m=5..36), normalise each occupied fundamental-quadrant
cell (x,y) to the unit square via ((x+0.5)/m, (y+0.5)/m), and re-bin onto the 37x37
fundamental quadrant. The resulting per-cell frequency is a heuristic prior of where
a cell is more likely to sit -- purely advisory, NOT a constraint.

Outputs:
  results/hint_heatmap_m37.json   (full data + metadata)
  hint_data.js                    (window.HINT_M37 = 37x37 array, for the HTML tool)
"""
import os, json, glob

HERE = os.path.dirname(os.path.abspath(__file__))
SOL_DIR = os.path.join(HERE, "results", "solutions")
M = 37

heat = [[0.0] * M for _ in range(M)]   # heat[x][y]
n_sol = 0
n_cells = 0
used = []

for path in sorted(glob.glob(os.path.join(SOL_DIR, "m*.json"))):
    with open(path, "r", encoding="utf-8") as f:
        d = json.load(f)
    m = d.get("m")
    cells = d.get("cells")
    if not m or not cells or m < 5:
        continue
    n_sol += 1
    used.append(m)
    for x, y in cells:
        nx = (x + 0.5) / m
        ny = (y + 0.5) / m
        gx = min(M - 1, int(nx * M))
        gy = min(M - 1, int(ny * M))
        heat[gx][gy] += 1.0
        n_cells += 1

# normalise to [0,1] by max cell
mx = max(max(row) for row in heat) or 1.0
heat_norm = [[round(heat[x][y] / mx, 4) for y in range(M)] for x in range(M)]

out_json = {
    "m": M,
    "source_solutions": used,
    "n_solutions": n_sol,
    "n_cells_binned": n_cells,
    "note": "advisory prior only; extrapolated from m=5..36 known rot4 solutions; NOT a constraint",
    "heat_raw_max": mx,
    "heat": heat_norm,   # heat[x][y] in [0,1]
}
os.makedirs(os.path.join(HERE, "results"), exist_ok=True)
with open(os.path.join(HERE, "results", "hint_heatmap_m37.json"), "w", encoding="utf-8") as f:
    json.dump(out_json, f)

with open(os.path.join(HERE, "hint_data.js"), "w", encoding="utf-8") as f:
    f.write("// auto-generated by generate_hint_heatmap.py -- advisory prior for m=37 builder\n")
    f.write("window.HINT_M37 = " + json.dumps(heat_norm) + ";\n")
    f.write("window.HINT_META = " + json.dumps({k: out_json[k] for k in
            ("source_solutions", "n_solutions", "n_cells_binned", "heat_raw_max")}) + ";\n")

print(f"solutions used: {n_sol} (m={used})")
print(f"cells binned  : {n_cells}")
print(f"max cell heat : {mx}")
print("wrote results/hint_heatmap_m37.json + hint_data.js")
