"""
Prove rct4 infeasibility for n=11,13,15 using Z3.

rct4 symmetry on odd n=2m+1 is generated by:
  R²(i,j) = (2m-i, 2m-j)   [180° rotation]  
  σ(i,j) = (j,i)            [diagonal reflection]

The V₄ group = {I, R², σ, σR²} partitions grid points into:
  - Center (m,m): size-1 orbit (fixed by all)
  - Main diagonal (i,i) where i≠m: size-2 orbits {(i,i), (2m-i,2m-i)}
  - Anti-diagonal (i,2m-i) where i≠m: size-2 orbits {(i,2m-i), (2m-i,i)}
  - General points: size-4 orbits

We encode: for each orbit, select ALL its points or NONE.
Constraints: 
  - Exactly 2n points selected
  - Each row has exactly 2 points  
  - Each column has exactly 2 points
  - No three collinear (checked only if all 3 points are selected)
"""

from collections import Counter
import itertools, sys

try:
    import z3
except ImportError:
    print("Z3 not installed. Installing...")
    import subprocess
    subprocess.run([sys.executable, "-m", "pip", "install", "z3-solver", "-q"])
    import z3

def build_rct4_encoding(n):
    """Build Z3 encoding for rct4 on odd n.
    Returns (solver, select_vars, orbit_info)"""
    m = (n-1)//2
    print(f"\n{'='*60}")
    print(f"Building rct4 encoding for n={n} (m={m})")
    print(f"{'='*60}")
    
    s = z3.Solver()
    
    # Generate all V₄ orbits
    # orbit[i] = list of points in the orbit
    # orbit_key[i] = canonical representation of the orbit
    orbits = []
    orbit_keys = set()
    orbit_sizes = Counter()
    
    for i in range(n):
        for j in range(n):
            # Skip if we've already processed this orbit
            if any((i,j) in orb for orb in orbits):
                continue
            
            # Generate V₄ orbit
            orb_set = set()
            orb_set.add((i,j))
            orb_set.add((n-1-i, n-1-j))  # R²
            orb_set.add((j,i))           # σ
            orb_set.add((n-1-j, n-1-i))  # σR²
            
            # Deduplicate
            orb_list = sorted(orb_set)
            
            if len(orb_list) == 1:  # center only
                orbits.append(orb_list)
                orbit_sizes[1] += 1
            elif len(orb_list) == 2:
                orbits.append(orb_list)
                orbit_sizes[2] += 1
            elif len(orb_list) == 4:
                orbits.append(orb_list)
                orbit_sizes[4] += 1
            else:
                print(f"  WARNING: Unexpected orbit size {len(orb_list)}")
    
    print(f"  V₄ orbit sizes: {dict(orbit_sizes)}")
    print(f"  Total orbits: {len(orbits)}")
    
    # Variables: x_k = 1 if orbit k is selected
    x = [z3.Bool(f'x_{k}') for k in range(len(orbits))]
    
    # Point -> orbit mapping
    point_to_orbit = {}
    for k, orb in enumerate(orbits):
        for p in orb:
            point_to_orbit[p] = k
    
    # Constraint 1: Total points = 2n
    # Each orbit of size s contributes s points
    total_pt_expr = z3.Sum([z3.If(x[k], len(orbits[k]), 0) for k in range(len(orbits))])
    s.add(total_pt_expr == 2*n)
    
    # Constraint 2: Each row has exactly 2 points
    for i in range(n):
        row_orbit_vars = set()
        for k, orb in enumerate(orbits):
            if any(p[0] == i for p in orb):
                row_orbit_vars.add(k)
        # Count contribution: each selected orbit contributes its points on this row
        row_expr = z3.Sum([z3.If(x[k], sum(1 for p in orbits[k] if p[0] == i), 0) 
                          for k in row_orbit_vars])
        s.add(row_expr == 2)
    
    # Constraint 3: Each column has exactly 2 points
    for j in range(n):
        col_orbit_vars = set()
        for k, orb in enumerate(orbits):
            if any(p[1] == j for p in orb):
                col_orbit_vars.add(k)
        col_expr = z3.Sum([z3.If(x[k], sum(1 for p in orbits[k] if p[1] == j), 0) 
                          for k in col_orbit_vars])
        s.add(col_expr == 2)
    
    # Constraint 4: No three collinear
    # Check ALL possible collinear triples across selected orbits:
    # Case A: 3 points from 3 different orbits (already handled)
    # Case B: 2 points from orbit k1 + 1 from orbit k2 (k1 ≠ k2)
    # Case C: 3 points all from the same orbit k (but we verified size-4 orbits
    #   have no internal collinear triples, so this is not needed)
    collinear_checks = 0
    collinear_forbidden = 0
    
    # Case A: 3 from 3 different orbits
    for k1 in range(len(orbits)):
        for k2 in range(k1+1, len(orbits)):
            for k3 in range(k2+1, len(orbits)):
                pts1, pts2, pts3 = orbits[k1], orbits[k2], orbits[k3]
                has_coll = False
                for p1 in pts1:
                    if has_coll: break
                    for p2 in pts2:
                        if has_coll: break
                        for p3 in pts3:
                            x1,y1=p1; x2,y2=p2; x3,y3=p3
                            if (x2-x1)*(y3-y1) == (x3-x1)*(y2-y1):
                                has_coll = True
                                break
                collinear_checks += 1
                if has_coll:
                    s.add(z3.Not(z3.And(x[k1], x[k2], x[k3])))
                    collinear_forbidden += 1
    
    # Case B: 2 points from orbit k1 + 1 point from orbit k2
    for k1 in range(len(orbits)):
        if len(orbits[k1]) < 2: continue  # size-1 orbit can't contribute 2 pts
        for k2 in range(len(orbits)):
            if k1 == k2: continue
            pts1 = orbits[k1]
            pts2 = orbits[k2]
            has_coll = False
            for a in range(len(pts1)):
                if has_coll: break
                for b in range(a+1, len(pts1)):
                    if has_coll: break
                    for p3 in pts2:
                        x1,y1=pts1[a]; x2,y2=pts1[b]; x3,y3=p3
                        if (x2-x1)*(y3-y1) == (x3-x1)*(y2-y1):
                            has_coll = True
                            break
            collinear_checks += 1
            if has_coll:
                s.add(z3.Not(z3.And(x[k1], x[k2])))
                collinear_forbidden += 1
    
    print(f"  Collinearity checks: {collinear_checks}")
    print(f"  Forbidden triples: {collinear_forbidden}")
    
    return s, x, orbits

def check_n(n, timeout=300):
    s, x, orbits = build_rct4_encoding(n)
    
    print(f"\n  Solving for n={n}...")
    s.set("timeout", timeout * 1000)
    result = s.check()
    
    if result == z3.sat:
        model = s.model()
        selected = [k for k in range(len(x)) if model[x[k]] == True]
        total_pts = sum(len(orbits[k]) for k in selected)
        print(f"  ✅ SAT: {len(selected)} orbits selected ({total_pts} points)")
        
        # Check missing-center
        ctr = (n-1)/2.0
        rings = Counter()
        for k in selected:
            for (i,j) in orbits[k]:
                d2 = int(round((i-ctr)**2 + (j-ctr)**2))
                rings[d2] += 1
        missing = all(v < 3 for v in rings.values())
        max_ring = max(rings.values())
        print(f"  Missing-center: {missing}, max ring pop: {max_ring}")
        return True
    elif result == z3.unsat:
        print(f"  ❌ UNSAT (no rct4 solution exists)")
        return False
    else:
        print(f"  ⏰ UNKNOWN (timeout {timeout}s)")
        return None

# Test
for n in [9, 11, 13, 15, 17, 19]:
    check_n(n, timeout=600)

print("\n\nDone!")
