#!/usr/bin/env python3
"""Exact CRT/rainbow verifier for finite no-three-in-line point sets.

Input JSON may contain either one case or a list of cases.  A case has

    {"name": "...", "n": 74, "points": [[x, y], ...]}

or, for an even C4-symmetric board n=2m,

    {"name": "...", "n": 74, "cells": [[a, b], ...]}

where ``cells`` are the m directed fundamental-square cells.  The script uses
two prime moduli p,q >= n with pq > (n-1)^2, so simultaneous modular
collinearity is equivalent to integer collinearity on the board.
"""

from __future__ import annotations

import argparse
import json
import math
from collections import defaultdict
from pathlib import Path
from typing import Iterable, Sequence

Point = tuple[int, int]
Line = tuple[int, int, int]
Colour = tuple[Line, Line]


def is_prime(value: int) -> bool:
    if value < 2:
        return False
    if value % 2 == 0:
        return value == 2
    divisor = 3
    while divisor * divisor <= value:
        if value % divisor == 0:
            return False
        divisor += 2
    return True


def next_prime(value: int) -> int:
    while not is_prime(value):
        value += 1
    return value


def choose_moduli(n: int) -> tuple[int, int]:
    """Return distinct primes p,q >= n with pq > (n-1)^2."""
    p = next_prime(n)
    q = next_prime(p + 1)
    while p * q <= (n - 1) ** 2:
        q = next_prime(q + 1)
    return p, q


def modular_line(a: Point, b: Point, prime: int) -> Line:
    """Canonical affine line A*x+B*y=C over F_prime."""
    if a == b:
        raise ValueError("a point pair must contain two different points")
    x1, y1 = a
    x2, y2 = b
    aa = (y1 - y2) % prime
    bb = (x2 - x1) % prime
    cc = (aa * x1 + bb * y1) % prime
    pivot = aa if aa else bb
    scale = pow(pivot, -1, prime)
    return aa * scale % prime, bb * scale % prime, cc * scale % prime


def integer_line(a: Point, b: Point) -> Line:
    """Canonical primitive integer line A*x+B*y=C."""
    x1, y1 = a
    x2, y2 = b
    aa = y1 - y2
    bb = x2 - x1
    divisor = math.gcd(abs(aa), abs(bb))
    aa //= divisor
    bb //= divisor
    if aa < 0 or (aa == 0 and bb < 0):
        aa, bb = -aa, -bb
    return aa, bb, aa * x1 + bb * y1


def expand_c4_cells(n: int, cells: Iterable[Sequence[int]]) -> list[Point]:
    if n % 2:
        raise ValueError("the C4 fundamental-square encoding requires even n")
    m = n // 2
    points: set[Point] = set()
    cells_list = [tuple(map(int, cell)) for cell in cells]
    if len(cells_list) != m:
        raise ValueError(f"expected {m} fundamental cells, got {len(cells_list)}")
    for a, b in cells_list:
        if not (0 <= a < m and 0 <= b < m):
            raise ValueError(f"fundamental cell {(a, b)} lies outside [0,{m})^2")
        orbit = (
            (a, b),
            (b, n - 1 - a),
            (n - 1 - a, n - 1 - b),
            (n - 1 - b, a),
        )
        if len(set(orbit)) != 4:
            raise ValueError(f"degenerate orbit generated by {(a, b)}")
        points.update(orbit)
    if len(points) != 2 * n:
        raise ValueError(f"expected {2*n} distinct expanded points, got {len(points)}")
    return sorted(points)


def direct_bad_triples(points: Sequence[Point]) -> int:
    """Count collinear triples from canonical integer pair-line buckets."""
    line_vertices: dict[Line, set[int]] = defaultdict(set)
    for i, a in enumerate(points):
        for j in range(i + 1, len(points)):
            key = integer_line(a, points[j])
            line_vertices[key].update((i, j))
    return sum(math.comb(len(vertices), 3) for vertices in line_vertices.values())


def crt_rainbow_statistics(
    points: Sequence[Point], p: int, q: int
) -> dict[str, int | bool]:
    """Count pair colours and recover the exact collinear-triple energy."""
    if p == q or not is_prime(p) or not is_prime(q):
        raise ValueError("p and q must be distinct primes")
    colour_vertices: dict[Colour, set[int]] = defaultdict(set)
    pair_count = 0
    for i, a in enumerate(points):
        for j in range(i + 1, len(points)):
            b = points[j]
            colour = (modular_line(a, b, p), modular_line(a, b, q))
            colour_vertices[colour].update((i, j))
            pair_count += 1

    colour_count = len(colour_vertices)
    collision_colours = 0
    bad_triples = 0
    for vertices in colour_vertices.values():
        size = len(vertices)
        if size >= 3:
            collision_colours += 1
            bad_triples += math.comb(size, 3)

    return {
        "pair_count": pair_count,
        "colour_count": colour_count,
        "repeated_colour_excess": pair_count - colour_count,
        "collision_colours": collision_colours,
        "bad_triples": bad_triples,
        "rainbow": pair_count == colour_count,
    }


def verify_case(case: dict) -> dict:
    name = str(case.get("name", "unnamed"))
    n = int(case["n"])
    if "points" in case:
        points = [tuple(map(int, point)) for point in case["points"]]
    elif "cells" in case:
        points = expand_c4_cells(n, case["cells"])
    else:
        raise ValueError(f"{name}: expected 'points' or 'cells'")

    if len(points) != len(set(points)):
        raise ValueError(f"{name}: duplicate selected points")
    if any(not (0 <= x < n and 0 <= y < n) for x, y in points):
        raise ValueError(f"{name}: a selected point lies outside the board")

    p = int(case.get("p", 0))
    q = int(case.get("q", 0))
    if not p or not q:
        p, q = choose_moduli(n)
    if min(p, q) < n or p * q <= (n - 1) ** 2:
        raise ValueError(f"{name}: CRT moduli do not satisfy the exactness bound")

    crt = crt_rainbow_statistics(points, p, q)
    direct = direct_bad_triples(points)
    if crt["bad_triples"] != direct:
        raise AssertionError(
            f"{name}: CRT count {crt['bad_triples']} != integer count {direct}"
        )

    point_count = len(points)
    baseline = 3 * point_count * point_count - 2 * point_count
    row_counts = [0] * n
    column_counts = [0] * n
    for x, y in points:
        row_counts[x] += 1
        column_counts[y] += 1
    return {
        "name": name,
        "n": n,
        "point_count": point_count,
        "two_per_row_and_column": all(value == 2 for value in row_counts)
        and all(value == 2 for value in column_counts),
        "p": p,
        "q": q,
        **crt,
        "direct_bad_triples": direct,
        "cubic_trace_baseline": baseline,
        "filtered_cubic_trace_average": baseline + 6 * direct,
    }


def self_test() -> None:
    cases = [
        {
            "name": "noncollinear",
            "n": 4,
            "points": [[0, 0], [0, 1], [1, 0], [2, 2]],
        },
        {
            "name": "one_collinear_triple",
            "n": 4,
            "points": [[0, 0], [1, 1], [2, 2], [0, 2]],
        },
    ]
    results = [verify_case(case) for case in cases]
    assert results[0]["bad_triples"] == 0
    assert results[0]["rainbow"] is True
    assert results[1]["bad_triples"] == 1
    assert results[1]["rainbow"] is False
    print(json.dumps(results, indent=2))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("json_file", nargs="?", type=Path)
    parser.add_argument(
        "--self-test", action="store_true", help="run two built-in exact checks"
    )
    args = parser.parse_args()
    if args.self_test:
        self_test()
        return
    if args.json_file is None:
        parser.error("provide a JSON case file or use --self-test")

    payload = json.loads(args.json_file.read_text(encoding="utf-8"))
    cases = payload if isinstance(payload, list) else [payload]
    print(json.dumps([verify_case(case) for case in cases], indent=2))


if __name__ == "__main__":
    main()
